project_id = "ttcnsnhsvrbthneyisfl"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false